# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/robot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/robot.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\" \n\tImageData\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\";\n\tRobotData\x12\x13\n\x04pose\x18\x01 \x01(\x0b\x32\x05.Pose\x12\x19\n\x05image\x18\x02 \x01(\x0b\x32\n.ImageData2B\n\x0cRobotService\x12\x32\n\x0cGetRobotData\x12\x16.google.protobuf.Empty\x1a\n.RobotDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=50
  _globals['_POSE']._serialized_end=91
  _globals['_IMAGEDATA']._serialized_start=93
  _globals['_IMAGEDATA']._serialized_end=125
  _globals['_ROBOTDATA']._serialized_start=127
  _globals['_ROBOTDATA']._serialized_end=186
  _globals['_ROBOTSERVICE']._serialized_start=188
  _globals['_ROBOTSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
